# Use postgres/example user/password credentials
version: '3.8'

services:
  hta_db:
    image: postgres:latest
    restart: always
    container_name: hta_db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: java_hta_db
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    expose:
      - 5432

