# Use postgres/example user/password credentials
version: '3.8'

services:
  hta_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: java_hta_db
    ports:
      - 5432:5432
    expose:
      - 5432
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready"]
#
#  hta_app:
#    build: .
#    depends_on:
#      hta_db:
#        condition: service_healthy
#    ports:
#      - 8080:8080
#    expose:
#      - 8080


