version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: Database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: planter_db
      POSTGRES_USER: admin
    volumes:
      - planter_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - planter_network

  # java:
  #   build: 
  #     context: ./java_backend
  #     dockerfile: dockerfile.backend
  #   container_name: Backend
  #   environment:
  #     - SPRING_DATASOURCE_USERNAME=admin
  #     - SPRING_DATASOURCE_PASSWORD=admin
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/planter_db
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - planter_network

  # typescript:
  #   build: 
  #     context: ./ts_frontend
  #     dockerfile: dockerfile.frontend
  #   container_name: Frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - planter_network

volumes:
  planter_volume:
   external: true

networks:
  planter_network:
