version: '3.8'

services:
  planter_db:
    image: postgres:latest
    restart: always
    container_name: planter_db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: planter_db
      POSTGRES_USER: admin
    volumes:
      - planter_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432

#  hta_app:
#    build: .
#    container_name: hta_app
#    depends_on:
#      - hta_db
#    environment:
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=admin
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://hta_db:5432/java_hta_db
#    ports:
#      - "8080:8080"

volumes:
  planter_db:

