version: '3.8'

services:
  planter_db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: planter_db
      POSTGRES_USER: admin
    volumes:
      - planter_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432

  planter_be:
   build: 
    context: ./java_backend
    dockerfile: dockerfile.backend
   container_name: be
   depends_on:
     - planter_db
   environment:
     - SPRING_DATASOURCE_USERNAME=admin
     - SPRING_DATASOURCE_PASSWORD=admin
     - SPRING_DATASOURCE_URL=jdbc:postgresql://planter_db:5432/planter_db
   ports:
     - "8080:8080"

  planter_fe:
   build: 
    dockerfile: dockerfile.frontend
   container_name: fe
   ports:
     - "3000:3000"

volumes:
  planter_db:

