spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java_hta_db
    password: admin
    username: admin
  jpa:
    hibernate:
      ddl-auto: create
