spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://planter_db_user:b0Sq58i416qoY7OItC90Vvn3GFRgT5jI@dpg-ckf6nj0l3its739fc8og-a.frankfurt-postgres.render.com/planter_db
    password: b0Sq58i416qoY7OItC90Vvn3GFRgT5jI
    username: planter_db_user
  jpa:
    hibernate:
      ddl-auto: create
