FROM eclipse-temurin:17-jdk

# Set the working directory
WORKDIR /app

# Copy your Spring Boot application source code into the container
COPY . /app

# Build the application
RUN ./mvnw clean package

# Expose the port that your Spring Boot app listens on
EXPOSE 8080

# Start the Spring Boot application
CMD ["java", "-jar", "target/planter-0.0.1.jar"]